// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcMasteryBlog.Data;

namespace MvcMasteryBlog.Migrations
{
    [DbContext(typeof(BlogContext))]
    [Migration("20191015204749_TagMigration")]
    partial class TagMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MvcMasteryBlog.Models.Blog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author");

                    b.Property<string>("Body");

                    b.Property<int>("Date");

                    b.Property<string>("Genre");

                    b.Property<string>("Image");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.ToTable("Blogs");

                    b.HasData(
                        new { ID = 1, Author = "Chef Bobby", Body = "Lorem Ipsum", Date = 2077, Genre = "Food", Image = "image", Title = "Food Blog" },
                        new { ID = 2, Author = "Chef Bobby", Body = "Lorem Ipsum", Date = 2077, Genre = "Food", Image = "image", Title = "Food Blog" }
                    );
                });

            modelBuilder.Entity("MvcMasteryBlog.Models.Tag", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BlogID");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.HasIndex("BlogID");

                    b.ToTable("Tags");

                    b.HasData(
                        new { ID = 1, BlogID = 1, Name = "Food" },
                        new { ID = 2, BlogID = 1, Name = "Chef" }
                    );
                });

            modelBuilder.Entity("MvcMasteryBlog.Models.Tag", b =>
                {
                    b.HasOne("MvcMasteryBlog.Models.Blog", "Blog")
                        .WithMany("Tags")
                        .HasForeignKey("BlogID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
