// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcMasteryBlog.Data;

namespace MvcMasteryBlog.Migrations
{
    [DbContext(typeof(BlogContext))]
    [Migration("20191014202826_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MvcMasteryBlog.Models.Blog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author");

                    b.Property<int?>("BlogID");

                    b.Property<string>("Body");

                    b.Property<int>("Date");

                    b.Property<string>("Genre");

                    b.Property<string>("Image");

                    b.Property<string>("Tags");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.HasIndex("BlogID");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("MvcMasteryBlog.Models.Blog", b =>
                {
                    b.HasOne("MvcMasteryBlog.Models.Blog")
                        .WithMany("Blogs")
                        .HasForeignKey("BlogID");
                });
#pragma warning restore 612, 618
        }
    }
}
